### ISSUE TITLE
Create Markdown Support to RSSG

### ISSUE THREAD

**Issue by roman-rezinkin** [Antonio-Bennett/rssg#6]
I want to introduce Markdown support to the rssg open source project. This support will allow the users to use not only .txt files but for .md files as well. The new feature will be able to parse a single Markdown feature into HTML.

Markdown Features could include:
Italics, Bold, Heading 1, Heading 2, or a Link.

Firstly, I will implement the ability for the tool to support .md files.
Secondly, I will be implementing the heading1 feature from Markdown syntax

**Comment by Antonio-Bennett** [comment]
Thank you Roman!

**Comment by Antonio-Bennett** [comment]
Hi Roman , thank you for your pull however after more testing I realized that there are some issues. 
1. The dist folder is not cleared when the program is ran
2. The bold tags are placed inside the p tags if there is no title or the markings are displayed in tags with title as seen below
![image](https://user-images.githubusercontent.com/31296212/134574856-3fb2c5c2-f1e4-41f4-9075-77c7a63a83b3.png)
![image](https://user-images.githubusercontent.com/31296212/134574918-11c6b802-740d-405a-8ace-5010d5884b18.png)

**Comment by roman-rezinkin** [comment]
I see, I wonder how I missed this. Could you provide me the .md file that you used for testing? I will address these issues today.

**Comment by roman-rezinkin** [comment]
I have also noted that I am missing the ability to detect the bold md syntax mid sentence. I am working on a fix for that as well.

**Comment by Antonio-Bennett** [comment]
Ahh okay cool feel free to pivot to a simper feature such as heading level as well if this functionality is too much

**Comment by Antonio-Bennett** [comment]
Thanks Roman for PR #9 great job
